### ISSUE TITLE
Expand readme.md

### ISSUE THREAD

**Issue by Zubnix** [ashleyj/aura#12]
Hi, this project looks promising. I would like to try it out but I don't really know where to start. Is it possible to expand the readme with:
- A brief description of the goals of this project (compared to other robovm forks)
- A 'getting started' ie how to compile simple java hello world to a native exectuable
- what is supported, what is not supported, on which platform it is supported
- know shortcomings
- ...

**Comment by ashleyj** [comment]
I'd like to keep things out of README.md where possible, so I've added a link to the wiki and expanded the content.

FAQ has been expanded to what is/isn't supported and the basic idea of aura
Using Aura shows you the command line args and how to compile HelloWorld.java

**Comment by Zubnix** [comment]
OK great, that will get me started.
